name: ci

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup pnpm
        uses: pnpm/action-setup@v4

      - name: install dependencies
        shell: bash
        run: pnpm install --frozen-lockfile

      - name: check site
        shell: bash
        run: pnpm run check

      - name: build site
        shell: bash
        run: pnpm run build
